# Dockerfile for Next.js
FROM node

# Set the working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --legacy-peer-deps

# Copy the application code
COPY . .

# Expose port (change if necessary)
EXPOSE 3000

# Enable Next.js in development mode
CMD ["npm", "run", "dev"]